INSERT OR IGNORE INTO items VALUES
(
  1,
  'Incepcja',
  'Inception',
  2010,
  '148 min',
  '["Sci-Fi","Thriller","Akcja"]',
  'Christopher Nolan',
  '["Leonardo DiCaprio","Marion Cotillard","Tom Hardy","Elliot Page"]',
  'movie',
  8.8,
  '[{"name":"Netflix","type":"Subskrypcja"},{"name":"HBO Max","type":"Subskrypcja"}]',
  'Dom Cobb jest najlepszym ze złodziei specjalizujących się w wykradaniu sekretów ze snów...'
),
(
  2,
  'Interstellar',
  'Interstellar',
  2014,
  '169 min',
  '["Sci-Fi","Drama","Adventure"]',
  'Christopher Nolan',
  '["Matthew McConaughey","Anne Hathaway","Jessica Chastain"]',
  'movie',
  8.6,
  '[{"name":"HBO Max","type":"Subskrypcja"},{"name":"Apple TV","type":"Subskrypcja"}]',
  'Grupa astronautów podróżuje przez kosmos, aby znaleźć nowy dom dla ludzkości.'
),
(3,
 'Matrix',
 'The Matrix',
 1999,
 '136 min',
 '["Sci-Fi","Akcja"]',
 'Lana Wachowski',
 '["Keanu Reeves","Carrie-Anne Moss","Laurence Fishburne"]',
 'movie',
 7.6,
 '[{"name":"Netflix","type":"Subskrypcja"}]',
 'Haker komputerowy Neo dowiaduje się, że świat, w którym żyje, jest tylko obrazem przesyłanym do jego mózgu.'
),
(4,
 'Gladiator',
 'Gladiator',
 2000,
 '155 min',
 '["Drama","Akcja"]',
 'Ridley Scott',
 '["Russell Crowe","Joaquin Phoenix","Connie Nielsen"]',
 'movie',
 7.6,
 '[{"name":"Amazon Prime","type":"Subskrypcja"}]',
 'Generał Maximus w jednej chwili traci wszystko. Jako niewolnik-gladiator musi walczyć na arenie o przeżycie.'
),
(5,
'Ojciec chrzestny',
'The Godfather',
1972,
'175 min',
'["Crime","Drama"]',
'Francis Ford Coppola',
'["Marlon Brando","Al Pacino","James Caan"]',
'movie',
9.1,
'[{"name":"Netflix","type":"Subskrypcja"},{"name":"SkyShowtime","type":"Subskrypcja"}]',
'Opowieść o nowojorskiej rodzinie mafijnej. Starzejący się Don Corleone pragnie przekazać władzę swojemu synowi.'
),
(
6,
'Skazani na Shawshank',
'The Shawshank Redemption',
1994,
'142 min',
'["Drama"]',
'Frank Darabont',
'["Tim Robbins","Morgan Freeman"]',
'movie',
8.2,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Niesłusznie skazany na dożywocie bankier, stara się przetrwać w brutalnym, więziennym świecie.'
),
(
7,
'Mroczny Rycerz',
'The Dark Knight',
2008,
'152 min',
'["Akcja","Crime","Sci-Fi"]',
'Christopher Nolan',
'["Christian Bale","Heath Ledger","Aaron Eckhart"]',
'movie',
8.0,
'[{"name":"HBO Max","type":"Subskrypcja"},{"name":"Amazon Prime","type":"Subskrypcja"}]',
'Batman, występuje przeciwko przerażającemu i nieobliczalnemu Jokerowi, który chce pogrążyć Gotham City w chaosie.'
),
(
8,
'Forrest Gump',
'Forrest Gump',
1994,
'142 min',
'["Drama","Comedy"]',
'Robert Zemeckis',
'["Tom Hanks","Robin Wright"]',
'movie',
7.9,
'[{"name":"Netflix","type":"Subskrypcja"},{"name":"SkyShowtime","type":"Subskrypcja"}]',
'Historia życia Forresta, chłopca o niskim ilorazie inteligencji, który staje się miliarderem i bohaterem wojny w Wietnamie.'
),
(
9,
'Władca Pierścieni: Drużyna Pierścienia',
'The Lord of the Rings: The Fellowship of the Ring',
2001,
'178 min',
'["Fantasy","Adventure"]',
'Peter Jackson',
'["Elijah Wood","Ian McKellen","Viggo Mortensen"]',
'movie',
8.3,
'[{"name":"Amazon Prime","type":"Subskrypcja"},{"name":"Netflix","type":"Subskrypcja"},{"name":"HBO Max","type":"Subskrypcja"}]',
'Podróż hobbita i jego ośmiu towarzyszy, której celem jest zniszczenie potężnego pierścienia pożądanego przez Czarnego Władcę - Saurona. '
),
(
10,
'Joker',
'Joker',
2019,
'122 min',
'["Crime","Drama","Thriller"]',
'Todd Phillips',
'["Joaquin Phoenix","Robert De Niro"]',
'movie',
7.2,
'[{"name":"HBO Max","type":"Subskrypcja"},{"name":"Amazon Prime","type":"Subskrypcja"},{"name":"Netflix","type":"Subskrypcja"}]',
'Strudzony życiem komik popada w obłęd i staje się psychopatycznym mordercą.'
),
(
11,
'Django',
'Django Unchained',
2012,
'165 min',
'["Western"]',
'Quentin Tarantino',
'["Jamie Foxx","Christoph Waltz","Leonardo DiCaprio"]',
'movie',
8.2,
'[{"name":"Apple TV","type":"Buy/Rent"}]',
'Łowca nagród Schultz i czarnoskóry niewolnik Django wyruszają w podróż, aby odbić żonę tego drugiego z rąk bezlitosnego Calvina.'
),
(
12,
'Avatar',
'Avatar',
2009,
'162 min',
'["Sci-Fi","Adventure"]',
'James Cameron',
'["Sam Worthington","Zoe Saldana","Stephen Lang"]',
'movie',
6.8,
'[{"name":"Disney+","type":"Subskrypcja"}]',
'Jake, sparaliżowany były komandos, zostaje wysłany na planetę Pandora, gdzie zaprzyjaźnia się z lokalną społecznością i postanawia jej pomóc.'
),
(
  101,
  'Breaking Bad',
  'Breaking Bad',
  2008,
  '62 odcinki',
  '["Crime","Drama","Thriller"]',
  'Vince Gilligan',
  '["Bryan Cranston","Aaron Paul","Anna Gunn"]',
  'series',
  9.5,
  '[{"name":"Netflix","type":"Subskrypcja"}]',
  'Nauczyciel chemii zostaje producentem narkotyków.'
),
(102,
 'Stranger Things',
 'Stranger Things',
 2016,
 '42 odcinki',
 '["Horror","Sci-Fi","Drama"]',
 'Duffer Brothers',
 '["Winona Ryder","David Harbour","Millie Bobby Brown"]',
 'series',
 7.4,
 '[{"name":"Netflix","type":"Subskrypcja"}]',
 'W miasteczku znika chłopiec. Mieszkańcy odkrywają tajemnicę sekretnych eksperymentów, sił nadprzyrodzonych i dziwnej dziewczynki.'
),
(103,
 'Wiedźmin',
 'The Witcher',
 2019,
 '32 odcinki',
 '["Fantasy","Adventure"]',
 'Lauren Schmidt Hissrich',
 '["Freya Allan","Anya Chalotra","Henry Cavill"]',
 'series',
 5.4,
 '[{"name":"Netflix","type":"Subskrypcja"}]',
 'Geralt z Rivii, łowca potworów, podąża ścieżką przeznaczenia w świecie, gdzie ludzie okazują się gorsi niż monstra.'
),
(
104,
'Gra o tron',
'Game of Thrones',
2011,
'79 odcinki',
'["Fantasy","Drama","Adventure"]',
'David Benioff',
'["Emilia Clarke","Kit Harington","Peter Dinklage"]',
'series',
7.9,
'[{"name":"HBO Max","type":"Subskrypcja"}]',
'Adaptacja sagi George''a R.R. Martina. W królestwie Westeros walka o władzę, spiski oraz zbrodnie są na porządku dziennym. '
),
(
105,
'Czarnobyl',
'Chernobyl',
2019,
'5 odcinków',
'["Drama","History"]',
'Craig Mazin',
'["Jared Harris","Stellan Skarsgård","Jessie Buckley"]',
'series',
9.2,
'[{"name":"HBO Max","type":"Subskrypcja"}]',
'Po wybuchu elektrowni jądrowej w Czarnobylu ratownicy poświęcają zdrowie i życie, by ratować Europę przed skutkami katastrofy.'
),
(
106,
'House of Cards',
'House of Cards',
2013,
'73 odcinki',
'["Drama","Politics"]',
'Beau Willimon',
'["Kevin Spacey","Robin Wright","Michael Kelly"]',
'series',
8.2,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Francis Underwood jest bezwzględnym politykiem próbującym się zemścić na prezydencie, który pominął go przy obsadzeniu stanowiska sekretarza stanu.'
),
(
107,
'Sherlock',
'Sherlock',
2010,
'12 odcinków',
'["Crime","Drama"]',
'Mark Gatiss',
'["Benedict Cumberbatch","Martin Freeman"]',
'series',
8.0,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Gdy John Watson poznaje genialnego detektywa Sherlocka Holmesa, zaczyna pomagać mu w rozwiązywaniu zagadek kryminalnych.'
),
(
108,
'Dark',
'Dark',
2017,
'26 odcinków',
'["Sci-Fi","Thriller"]',
'Baran bo Odar',
'["Louis Hofmann","Lisa Vicari","Karoline Eichhorn"]',
'series',
7.6,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Zaginięcie dzieci ujawnia podwójne życie i nadszarpnięte relacje członków czterech rodzin, łącząc się z wydarzeniami sprzed trzydziestu lat.'
),
(
109,
'The Last of Us',
'The Last of Us',
2023,
'16 odcinków',
'["Drama","Sci-Fi","Horror"]',
'Craig Mazin',
'["Pedro Pascal","Bella Ramsey"]',
'series',
7.4,
'[{"name":"HBO Max","type":"Subskrypcja"}]',
'Gdy globalna pandemia niszczy cywilizację, ocalały przejmuje opiekę nad 14-letnią dziewczyną, która może być ostatnią nadzieją ludzkości'
),
(
110,
'Peaky Blinders',
'Peaky Blinders',
2013,
'36 odcinków',
'["Crime","Drama"]',
'Steven Knight',
'["Cillian Murphy","Helen McCrory","Paul Anderson"]',
'series',
7.7,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Gangsterska rodzina w powojennej Anglii.'
),
(
111,
'Narcos',
'Narcos',
2015,
'30 odcinków',
'["Crime","Drama"]',
'Carlo Bernard',
'["Wagner Moura","Pedro Pascal","Boyd Holbrook"]',
'series',
7.8,
'[{"name":"Netflix","type":"Subskrypcja"}]',
'Dwaj agenci zostają wysłani do Kolumbii, aby zakończyć działalność handlarza narkotyków.'
),
(
113,
'Dexter',
'Dexter',
2006,
'96 odcinków',
'["Crime","Drama"]',
'James Manos Jr.',
'["Michael C. Hall","Jennifer Carpenter","David Zayas"]',
'series',
7.2,
'[{"name":"SkyShowtime","type":"Subskrypcja"}]',
'Dexter prowadzi podwójne życie. Za dnia jest cenionym specjalistą ds. krwi w departamencie policji, a nocą zabija złoczyńców, którzy wymykają się organom sprawiedliwości.'
),
(
114,
'The Office',
'The Office',
2005,
'204 odcinków',
'["Comedy"]',
'Ricky Gervais',
'["Jenna Fisher","Steve Carell","John Krasinski","Rainn Wilson"]',
'series',
9.0,
'[{"name":"Netflix","type":"Subskrypcja"},{"name":"Disney+","type":"Subskrypcja"},{"name":"Amazon Prime","type":"Subskrypcja"}]',
'Kamery towarzyszą pracownikom oddziału firmy sprzedającej artykuły papierowe w czasie ich codziennych obowiązków..'
);

INSERT OR IGNORE INTO genres (genre) VALUES ('Sci-Fi');
INSERT OR IGNORE INTO genres (genre) VALUES ('Thriller');
INSERT OR IGNORE INTO genres (genre) VALUES ('Akcja');
INSERT OR IGNORE INTO genres (genre) VALUES ('Drama');
INSERT OR IGNORE INTO genres (genre) VALUES ('Adventure');
INSERT OR IGNORE INTO genres (genre) VALUES ('Comedy');
INSERT OR IGNORE INTO genres (genre) VALUES ('Crime');
INSERT OR IGNORE INTO genres (genre) VALUES ('Fantasy');
INSERT OR IGNORE INTO genres (genre) VALUES ('Horror');
INSERT OR IGNORE INTO genres (genre) VALUES ('History');
INSERT OR IGNORE INTO genres (genre) VALUES ('Politics');
INSERT OR IGNORE INTO genres (genre) VALUES ('Western');

INSERT OR IGNORE INTO platforms (platform, type) VALUES ('Netflix', 'Subskrypcja');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('HBO Max', 'Subskrypcja');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('Apple TV', 'Subskrypcja');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('Apple TV', 'Buy/Rent');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('Amazon Prime', 'Subskrypcja');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('SkyShowtime', 'Subskrypcja');
INSERT OR IGNORE INTO platforms (platform, type) VALUES ('Disney+', 'Subskrypcja');
